mysite/datafile/urls.py
from django.conf.urls import url
from . import views

app_name = 'datafile' #add name space for {% url %}
#wire the views into the urls
urlpatterns = [
    # file management
    url(r'^$', views.projects_overview, name="projects_overview"),
    url(r'^(?P<projectName>[\w ]+)/$', views.project_detail, name="project_detail"),
    url(r'^(?P<projectName>[\w ]+)/upload_glm/$', views.upload_glm, name="upload_glm"),
    url(r'^(?P<projectName>[\w ]+)/(?P<feederName>[\w ]+)/convert_glm$', views.convert_glm, name='convert_glm'),
    url(r'^(?P<projectName>[\w ]+)/(?P<feederName>[\w ]+)/glm_out$', views.glm_out, name='glm_out'),
    #json data
    url(r'^(?P<projectName>[\w ]+)/(?P<feederName>[\w ]+)/get_pg_json$', views.get_pg_json, name='get_pg_json'),
    url(r'^(?P<projectName>[\w ]+)/(?P<feederName>[\w ]+)/save_pg_json$', views.save_pg_json, name='save_pg_json'),
    url(r'^(?P<projectName>[\w ]+)/(?P<feederName>[\w ]+)/get_vis_json$', views.get_vis_json, name='get_vis_json'),
    url(r'^(?P<projectName>[\w ]+)/(?P<feederName>[\w ]+)/save_vis_json$', views.save_vis_json, name='save_vis_json'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# for serving the media file during development
# https://timmyomahony.com/blog/static-vs-media-and-root-vs-path-in-django/
from django.conf import settings
from django.conf.urls.static import static

# serve the home page
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^admin/', admin.site.urls),
    url(r'projects/', include('datafile.urls')),
    url(r'pgnetwork/', include('pgnetwork.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/datafile/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/datafile/forms.py
from django import forms
# from django.core.exceptions import ValidationError
# from distribution.models import Feeder
from django.utils.safestring import mark_safe

class UploadGLMForm(forms.Form):
    feeder_name = forms.CharField(max_length=50, help_text=mark_safe("input a <b>UNIQUE</b> feeder name<br/> (e.g. PG_CASE_123)"))
    glm_file = forms.FileField()
    def clean_feeder_name(self):
        feederName = self.cleaned_data['feeder_name']
        # print 'checking valid data for subject ', data
        # if Feeder.objects.filter(name=feederName).exists():
        #     raise ValidationError("Feeder Name Exists, please input a Unique Name")
        return feederName

mysite/datafile/views/jsondata.py
# from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

import os, json
from django.conf import settings
BASE_DIR = settings.BASE_DIR
MEDIA_URL = settings.MEDIA_URL
DATA_DIR = os.path.join(BASE_DIR, 'data')
PROJECTS_DIR = os.path.join(DATA_DIR, 'Projects')


# serve the pgjson
def get_pg_json(request, projectName, feederName):
    PG_JSON_DIR = os.path.join(PROJECTS_DIR, projectName, feederName, 'json', 'pg.json')
    with open(PG_JSON_DIR, "r") as infile:
        data = json.load(infile)
        return JsonResponse(data, safe=False)
    return HttpResponse(status=404) #fail

# save pgjson
@csrf_exempt
def save_pg_json(request, projectName, feederName):
    if request.is_ajax():
        if request.method == 'POST':
            PG_JSON_DIR = os.path.join(PROJECTS_DIR, projectName, feederName, 'json', 'pg.json')
            with open(PG_JSON_DIR, 'w') as outfile:
                data = json.loads(request.body)
                json.dump(data, outfile, indent=4)
            return HttpResponse(status=204) #success,no content return
    return HttpResponse(status=404) #success,no content return


# serve vis json
def get_vis_json(request, projectName, feederName):
    VIS_JSON_DIR = os.path.join(PROJECTS_DIR, projectName, feederName, 'json', 'vis.json')
    with open(VIS_JSON_DIR, "r") as infile:
        data = json.load(infile)
        return JsonResponse(data, safe=False)
    return HttpResponse(status=404) #fail

# save vis json
@csrf_exempt
def save_vis_json(request, projectName, feederName):
    if request.is_ajax():
        if request.method == 'POST':
            VIS_JSON_DIR = os.path.join(PROJECTS_DIR, projectName, feederName, 'json', 'vis.json')
            with open(VIS_JSON_DIR, 'w') as outfile:
                data = json.loads(request.body)
                json.dump(data, outfile, indent=4)
    return HttpResponse(status=204) #success,no content return

mysite/datafile/views/management.py
from django.shortcuts import render
from ..forms import UploadGLMForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from ..utils.helpers import createVisJson
from django.urls import reverse

# Create your views here.

# the helper function to parse/export the glm file
from OpenSourceParser import ImportGLM, ExportGLM

import os, json, datetime
from django.conf import settings
BASE_DIR = settings.BASE_DIR
MEDIA_URL = settings.MEDIA_URL
DATA_DIR = os.path.join(BASE_DIR, 'data')
PROJECTS_DIR = os.path.join(DATA_DIR, 'Projects')

def safeListdir(path):
    ''' Helper function that returns [] for dirs that don't exist. Otherwise new users can cause exceptions. '''
    try: return [x for x in os.listdir(path) if not x.startswith(".") and os.path.isdir(os.path.join(path, x))]
    except: return []

'''
Projects Overview /projects/ 
@get and post a list of projects
'''
def projects_overview(request):
    error_msg = None
    success_msg = None
    if request.method == 'POST':
        new_project_name = request.POST.get('project_name')
        print 'hello the input is ', new_project_name
        if (
            '.' in new_project_name or
            ' ' in new_project_name or
            new_project_name in safeListdir(PROJECTS_DIR)
        ):
            if '.' in new_project_name:
                error_msg = 'invalid project name!'
            if ' ' in new_project_name:
                error_msg = 'no space in project name please!'
            if new_project_name in safeListdir(PROJECTS_DIR):
                error_msg = 'duplicate project name!'
        else:
            #create project folder
            createNewProject(new_project_name)
            success_msg = '%s is created!' % new_project_name
    projects = [{'projectName': x} for x in safeListdir(PROJECTS_DIR)]
    # loop through the projects to get the meta data (the project must have meta data!!)
    for project in projects:
        #TODO: why we use try catch instead of with open?
        try:
            projectPath = os.path.join(PROJECTS_DIR, project['projectName'])
            metaData = json.load(open(os.path.join(projectPath, 'project_meta.json')))
            project['status'] = metaData.get('status', "N/A")
            project['type'] = metaData.get('type', "N/A")
            project['created'] = metaData.get('created', "N/A")
            project['der_valuation'] = metaData.get('der_valuation', None)
        except Exception:
            print Exception
            continue
    return render(request, 'datafile/projects_overview.html', 
        {'projects': projects, 'error_msg': error_msg, 'success_msg': success_msg})

'''
helper function to create new project folder
'''
def createNewProject(new_project_name, ):
    PROJECT_DIR = os.path.join(PROJECTS_DIR, new_project_name);
    os.makedirs(PROJECT_DIR)
    
    currTime = datetime.datetime.now().strftime('%Y/%m/%d %H:%M:%S')
    #create meta json
    project_meta = {
        "name": new_project_name,
        "type": "Power Flow",
        "status": "N/A",
        "created": currTime
    }
    with open(os.path.join(PROJECT_DIR, 'project_meta.json'), 'w') as infile:
        json.dump(project_meta, infile, indent=4)


'''
Project Detail /projects/projectName

the project detail, which show all the feeders in the current project
'''
def project_detail(request, projectName):
    PROJECT_DIR = os.path.join(PROJECTS_DIR, projectName)
    feeders = []
    'list all the feeder in the current project folder'
    feeders = [{'feederName': x} for x in safeListdir(PROJECT_DIR)]
    # loop through the feeders to get the meta data (the file must have meta data!!)
    for feeder in feeders:
        #TODO: why we use try catch instead of with open?
        try:
            FEEDER_DIR = os.path.join(PROJECT_DIR, feeder['feederName'])
            metaData = json.load(open(os.path.join(FEEDER_DIR, 'meta.json')))
            feeder['glmname'] = metaData.get('glmname', "N/A")
            feeder['json'] = metaData.get('json', "N/A")
            # if Feeder.objects.filter(name=feeder['feederName']).exists():
            feeder['explore'] = {
                #reverse with name space
                "tableview": reverse('pgnetwork:tableview', kwargs={'projectName': projectName, 'feederName': feeder['feederName']}),
            }
            # else:
                # feeder['explore'] = False
            feeder['supplemental'] = metaData.get('supplemental', "N/A")
        except:
            print 'SOME ERROR'
            continue
    return render(request, 'datafile/project_detail.html', {'feeders': feeders, 'projectName': projectName})



'''
Upload GLM to a feeder
'''
def upload_glm(request, projectName):
    if request.method == 'POST':
        form = UploadGLMForm(request.POST, request.FILES)
        if form.is_valid():
            feederName = form.cleaned_data['feeder_name']
            handle_uploaded_glm(projectName, feederName, request.FILES['glm_file'])
            the_url = reverse('datafile:project_detail', kwargs={'projectName': projectName})
            return HttpResponseRedirect(the_url)
    else:
        form = UploadGLMForm()
    return render(request, 'datafile/upload_glm.html', {'form': form, 'projectName': projectName})

'''
createNewFeeder
set up the basic folder structure for feeder
1. create a folder for the new feeder & 
2. create json & glmIn & glmOut & supplemental folders
3. save the metajson
'''
def createNewFeederFolder(projectName, feederName, glmFile):
    FEEDER_DIR = os.path.join(PROJECTS_DIR, projectName, feederName)
    os.makedirs(FEEDER_DIR)

    #create json/glmIn/glmOut/supplemental folders
    folders = ['json', 'glmIn', 'glmOut', 'supplemental'];
    for folder in folders:
        FOLDER_DIR = os.path.join(FEEDER_DIR, folder);
        os.makedirs(FOLDER_DIR)

    #create meta json
    metaJson = {
        "glmname": glmFile.name,
        "json": "YES",
        "supplemental": "N/A"
    }

    with open(os.path.join(FEEDER_DIR, 'meta.json'), 'w') as infile:
        json.dump(metaJson, infile, indent=4)

    return FEEDER_DIR
'''
handle_uploaded_glm
//it means creating a new feeder currently
1. create a folder for the new feeder
2. save the glm to glmIn folder
4. convert the glm and save the json output to the json folder
'''
def handle_uploaded_glm(projectName, feederName, glmFile):
    print 'handle_uploaded file!...should be async'
    # create the feeder folder
    FEEDER_DIR = createNewFeederFolder(projectName, feederName, glmFile)


    # # write the glm file to the glmIn folder (TODO: maybe always name input glm as 'main.glm')
    GLM_IN_FILE_DIR = os.path.join(FEEDER_DIR, 'glmIn', 'main.glm')
    with open(GLM_IN_FILE_DIR, 'wb+') as destination:
        for chunk in glmFile.chunks():
            destination.write(chunk)

    JSON_DIR = os.path.join(FEEDER_DIR, 'json')
    convertGLM2JSON(GLM_IN_FILE_DIR, JSON_DIR)
    return True

'''
helper function to prepare the require json files for a given glm
1. pg.json (the output of ImportGLM parser, the source of everything, including visible network and info)
2. vis.json (only include the vis data)
'''
def convertGLM2JSON(glmPath, JSON_DIR):
    pythonDict = ImportGLM(glmPath)
    # save this in memory dict to somewhere else if you worry about the open source problem

    pgJson = pythonDict
    # save the pgjson as the ONLY SOURCE of glm data for frontend!!
    with open(os.path.join(JSON_DIR, 'pg.json'), 'w') as outFile:
        json.dump(pgJson, outFile, indent=4)

    visJson = createVisJson(pgJson)
    with open(os.path.join(JSON_DIR, 'vis.json'), 'w') as outFile:
        json.dump(visJson, outFile, indent=4)
    return True



'''
convert data source(pgJson) to glm file and save it in glmOut folder
'''
def convert_glm(request, projectName, feederName):
    msg = 'Fail'
    FEEDER_DIR = os.path.join(PROJECTS_DIR, projectName, feederName)
    if not os.path.isdir(FEEDER_DIR):
        return HttpResponse(status=404)
    #findGLM_OUT_DIR
    GLM_OUT_DIR = os.path.join(FEEDER_DIR, 'glmOut')
    if os.path.isdir(GLM_OUT_DIR):
        print 'you are updating it'
        # return HttpResponse('the rawOut is available', status=200)
    else:
        os.makedirs(GLM_OUT_DIR)

    #The data source(might be database later)
    PGJSON_DIR = os.path.join(FEEDER_DIR, 'json', 'pg.json')
    #Use the current pgJson to make the glm string
    glmString = ExportGLM(PGJSON_DIR)

    #save the glm to glmOut folder
    currTime = datetime.datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
    glmName = "%s.main.glm" % (currTime)
    with open(os.path.join(GLM_OUT_DIR, glmName), 'w') as glmFile:
        glmFile.write(glmString)
        msg = 'Success'
    return HttpResponse(msg, status=200)


'''
display the glm out
'''
from urllib import quote
def glm_out(request, projectName, feederName):
    FEEDER_DIR = os.path.join(PROJECTS_DIR, projectName, feederName)
    # prepare the glmOutFolder if it is not created
    GLM_OUT_DIR = os.path.join(FEEDER_DIR, 'glmOut')
    # http://stackoverflow.com/questions/3964681/find-all-files-in-a-directory-with-extension-txt-in-python
    # http://stackoverflow.com/questions/120951/how-can-i-normalize-a-url-in-python
    allGlmFiles = [
        {
            "group": x.split('.')[0],
            "name": x, 
            "path": quote(os.path.join(MEDIA_URL, 'Projects', projectName, feederName, 'glmOut', x)) #this is the actual url
        } for x in os.listdir(GLM_OUT_DIR) if x.endswith(".glm")
    ]
    glmFilesGroup = {}
    for item in allGlmFiles:
        if not item['group'] in glmFilesGroup:
            glmFilesGroup[item['group']] = []
        glmFilesGroup[item['group']].append(item)

    return render(request, 'datafile/glm_out.html', {
        'glmFilesGroup': glmFilesGroup,
        'projectName': projectName,
        'feederName': feederName
    })

mysite/datafile/templates/datafile/glm_out.html
{% extends "base.html" %}
{% block title %}Project Detail {{projectName}} {% endblock %}  
{% block css-head %}{% endblock %}
{% block js-head %}{% endblock %}
{% block content %}
  <ol class="breadcrumb" style="margin-left:-15px;margin-right:-15px;margin-bottom: 5px">
    <li><a href="/">Home</a></li>
    <li><a href="{% url 'datafile:projects_overview' %}">Projects Overview</a></li>
    <li><a href="{% url 'datafile:project_detail' projectName=projectName %}">Project Detail</a></li>
    <li class="active">Generated GLM</li>
  </ol>

  {% for groupName, glmFiles in glmFilesGroup.items %}
    <h3><span class="label label-success">{{groupName}}</span></h3>
    <ul class="list-group">
      {% for file in glmFiles %}
        <li class="list-group-item">
          <a href={{file.path}}><i class="fa fa-download" aria-hidden="true"></i></a>
          {{file.name}}
        </li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endblock %} 
{% block js-foot %}{% endblock %}

mysite/datafile/templates/datafile/project_detail.html
{% extends "base.html" %}
{% block title %}Project Detail {{projectName}} {% endblock %}  
{% block css-head %}
<style type="text/css">
.map-explorer:hover .secrete {
  /*margin: 10px auto;*/
  display: inline;
}

.secrete {
  color: lime;
  font-weight: 900;
  display: none;
}

</style>
{% endblock %}
{% block js-head %}{% endblock %}
{% block content %}
  <ol class="breadcrumb" style="margin-left:-15px;margin-right:-15px;margin-bottom: 5px">
    <li><a href="/">Home</a></li>
    <li><a href="{% url 'datafile:projects_overview' %}">Projects Overview</a></li>
    <li class="active">Project Detail</li>
  </ol>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Feeder Name</th>
          <th>Glm Name</th>
          <th>JSON</th>
          <th>Supplemental</th>
          <th>Explore</th>
          <th>Convert GLM</th>
        </tr>
      </thead>
      <tbody>
        {% for feeder in feeders %}
          <tr> 
            <td>{{ feeder.feederName }}</td>
            <td>
              <a href="">
              {{ feeder.glmname }}
              </a>
            </td>
            <td>{{ feeder.json }}</td>
            <td>{{ feeder.supplemental }}</td>
            <td>
              {% if feeder.explore %}
                <a href={{feeder.explore.tableview}} target="_blank" class="btn btn-success">
                  Table
                </a>
              {% else %}
              N/A
              {% endif %}
            </td>
            <td>
              <button class="btn btn-primary" onClick="convertToGlm('{{projectName}}', '{{feeder.feederName}}')">
                <i class="fa fa-floppy-o"></i>
              </button>
              &nbsp;&nbsp;&nbsp;
              <a href="{% url 'datafile:glm_out' projectName=projectName feederName=feeder.feederName %}" class="btn btn-warning">
                <i class="fa fa-download"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'datafile:upload_glm'  projectName=projectName %}" class="btn btn-info">
      <i class="fa fa-upload"></i>
      Upload New GLM
    </a>

    <a href="#" class="btn btn-danger pull-right map-explorer disabled">
      <i class="fa fa-globe"></i>
      Explore Whole Project on Google Map
      <br/>
      <span class="secrete">GPS data required!</span>
    </a>

{% endblock %} 


{% block js-foot %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script type="text/javascript">
function convertToGlm(projectName, feederName) {
  var url = "/projects/" + projectName + "/" + feederName + "/convert_glm";
  $.ajax(
    {
      url: url, 
      success: function(result){
        console.log(result);
      }
    }
  );
}
</script>
{% endblock %}

mysite/datafile/templates/datafile/projects_overview.html
{% extends "base.html" %}
{% block title %}All Projects{% endblock %}
{% block css-head %}{% endblock %}
{% block js-head %}{% endblock %}  
{% block content %}
  <ol class="breadcrumb" style="margin-left:-15px;margin-right:-15px;margin-bottom: 5px">
    <li><a href="/">Home</a></li>
    <li class="active"><a href="{% url 'datafile:projects_overview' %}">Projects Overview</a></li>
  </ol>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Project Name</th>
          <th>Type</th>
          <th>Status</th>
          <th>Created</th>
          <th>DER Valuation</th>
        </tr>
      </thead>
      <tbody>
        {% for project in projects %}
          <tr> 
            <th>
            <a href="{% url 'datafile:project_detail' projectName=project.projectName %}">
              {{ project.projectName }}
            </a>
            </th>
            <td>
              {{ project.type }}
            </td>
            <td>{{ project.status }}</td>
            <td>{{ project.created }}</td>
            <td>
              {% if project.der_valuation %}
              <a href="#" target="_blank" class="btn btn-success btn-xs">
                  <i class="fa fa-bar-chart" aria-hidden="true"></i>
              </a>
              {% else %}
              N/A
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <form class="navbar-form navbar-left" action="" method="post">
      {% csrf_token %}
      <div class="form-group">
        <select class="form-control" id="project-type">
          <option>Power Flow</option>
          <option>DER Valuation</option>
        </select>
      </div>
      <div class="form-group">
        <input type="text" class="form-control" name="project_name" placeholder="New_Project_Name">
      </div>
      <button type="submit" class="btn btn-success">Create!</button>
    </form>

    {% if error_msg %}
    <div class="alert alert-danger">
      <strong>Sorry!</strong> {{error_msg}}
    </div>
    {% elif success_msg %}
    <div class="alert alert-success">
      <strong>Success!</strong> {{error_msg}}
    </div>
    {% endif %}
{% endblock %}
{% block js-foot %}{% endblock %}

mysite/datafile/templates/datafile/upload_glm.html
{% extends "base.html" %}
{% block title %}Upload GLM {{projectName}}{% endblock %} 
{% block css-head %} 
<style type="text/css">
.center {
  width: 400px;
  margin: 10px auto;
}
</style>
{% endblock %}
{% block js-head %}{% endblock %}
{% block content %}
      <ol class="breadcrumb" style="margin-left:-15px;margin-right:-15px;margin-bottom: 5px">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'datafile:projects_overview' %}">Projects Overview</a></li>
        <li><a href="{% url 'datafile:project_detail' projectName=projectName %}">Project Detail</a></li>
        <li class="active">Upload GLM</li>
      </ol>
      <!-- <div class="row"> -->
        <div class="center">
          <h3>Glm File Upload for Project: {{projectName}}</h3>
          <form enctype="multipart/form-data" action="{% url 'datafile:upload_glm' projectName=projectName %}" method="post">
            {% csrf_token %}
            <table class="table">
              {{form}}
            </table>
            <a href="{% url 'datafile:project_detail' projectName=projectName %}" class="btn btn-warning">
              Cancel
            </a>
            <input class="btn btn-primary pull-right" type="submit" value="upload" />
          </form>
        </div>
      <!-- </div> -->
{% endblock %}
{% block js-foot %}{% endblock %}